backend:
  name: git-gateway
  branch: main
  site_domain: https://resilient-entremet-55d6a6.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "entries"
    label: "Diary Entries"
    folder: "src/content/entries"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Spotify Embed", name: "spotify", widget: "string", required: false }
